all code page ka
ThisTine/detectivexiii-frontend pull request #12
Opened 2022-07-12 11:55 UTC by wtyaumm

2022-07-14 17:03 UTC, ThanadonTee requested changes

2022-07-14 17:03 UTC, ThanadonTee commented on src/pages/Code.tsx
> +    end: new Date(new Date().getTime() + 1 * 60000),
@ThisTine Suggestion to use [dayjs](https://github.com/iamkun/dayjs/)

2022-07-14 17:03 UTC, ThanadonTee commented on src/pages/Code.tsx
> +    const now = new Date().getTime();
switch to `Date.now()`

2022-07-14 17:03 UTC, ThanadonTee commented on src/pages/Code.tsx
> +      if (countdown() <= 0) {
if implemented with dayjs, you can just use `.isBefore()` to check instead of `countdown()`

2022-07-17 11:33 UTC, ThanadonTee approved these changes

2022-07-18 03:57 UTC, ThanadonTee commented
Approved na. Merge whenever you want @ThisTine

2022-07-20 09:21 UTC, ThisTine commented
@wtyaumm เค้าขอโทษ ~~ ดันทำระยำกับไฟล์ code ไว้ ;-; ฝากหมวยมี่ merge develop ลง branch ตัวเองก่อนเพื่อแก้ config ได้มะ ;-;

2022-07-22 08:54 UTC, merged