Fxh hint
ThisTine/detectivexiii-frontend pull request #6
Opened 2022-07-09 15:32 UTC by fxhPhxrxchxyx

2022-07-09 15:45 UTC, ThisTine requested changes
เค้าว่าน่าจะผิดไฟล์นิดหน่อยนะ เหมือนว่าฟ้าจะทำ Setup.tsx นะไม่ใช่ Hints.tsx

2022-07-09 15:45 UTC, ThisTine commented on package.json
> +    "@chakra-ui/icons": "^2.0.2",
เอ๋ icon จาก react-icons ไม่มีหรอ ? ;-;

2022-07-09 17:31 UTC, fxhPhxrxchxyx commented
> เค้าว่าน่าจะผิดไฟล์นิดหน่อยนะ เหมือนว่าฟ้าจะทำ Setup.tsx นะไม่ใช่ Hints.tsx

โอ้วโน้วว โอเชเคิ้บ

2022-07-09 17:32 UTC, fxhPhxrxchxyx commented on package.json
> +    "@chakra-ui/icons": "^2.0.2",
แงมะเห็นปายดูใหม่แปปคั้บ

2022-07-09 18:39 UTC, fxhPhxrxchxyx commented
ย้ายไฟล์แน้วค้าบ

2022-07-10 05:24 UTC, fxhPhxrxchxyx commented
setup outline

2022-07-11 08:40 UTC, closed without merging