Hint list final draft #1
ThisTine/detectivexiii-frontend pull request #7
Opened 2022-07-10 06:38 UTC by jigneng1

review ให้หน่อยครับ

2022-07-10 07:05 UTC, ThisTine requested changes
ฝากแก้นิดนึงงง

2022-07-10 07:05 UTC, ThisTine commented on src/components/HintCards.tsx
> +function HintCards({hints }:any) {
ฝากใส่ type ของ hint ให้นิดนึง

2022-07-10 07:05 UTC, ThisTine commented on src/components/HintCards.tsx
> +  if(hints.isShow){
ตรงนี้เปลี่ยนไปใช้ if else แบบ inline ได้มะ เค้าเห็นว่า component มันเหมือนกันมาก ๆ เลย ถ้า merge รวมเป็นอันเดียวได้เลยจะดีมาก (มีตัวอย่างอยู่ข้างล่างนะ)

2022-07-10 07:05 UTC, ThisTine commented on src/components/HintCards.tsx
> +            <Icon as={FaCheck}></Icon>
<Icon as={hints.isShow ? FaCheck : FaLock} />

2022-07-10 07:05 UTC, ThisTine commented on src/components/HintCards.tsx
> +          Unlocked
{ hints.isShow ? "Unlocked" : "Locked" }

2022-07-10 07:05 UTC, ThisTine commented on src/pages/Hints.tsx
> +      <Modal isOpen={isOpen} onClose={onClose} isCentered>
**optional** ถ้าทำได้ฝากแยก Modal ไปไว้ในอีก component ได้มะ มันน่าจะดูง่ายกว่า

2022-07-10 08:15 UTC, jigneng1 commented on src/components/HintCards.tsx
> +  if(hints.isShow){
done!

2022-07-10 08:15 UTC, jigneng1 commented on src/components/HintCards.tsx
> +            <Icon as={FaCheck}></Icon>
done!

2022-07-10 08:15 UTC, jigneng1 commented on src/components/HintCards.tsx
> +          Unlocked
done!

2022-07-10 09:23 UTC, jigneng1 commented on src/pages/Hints.tsx
> +      <Modal isOpen={isOpen} onClose={onClose} isCentered>
อันนี้ไม่สามารถทำได้อะเพราะ มันรับ function หลายตัว ถ้าจะทำอาจจะต้อง props มันไปทั้งหมด ไม่รู้ว่าใช่ป่าว555

2022-07-10 10:13 UTC, ThisTine commented on src/pages/Hints.tsx
> +      <Modal isOpen={isOpen} onClose={onClose} isCentered>
อะเชช งั้นไม่เป็นไร ๆ

2022-07-10 10:14 UTC, ThisTine requested changes

2022-07-10 10:14 UTC, ThisTine commented on src/components/HintCards.tsx
> +function HintCards({ hints }: any) {
เหลือ type ของ hints นะ

2022-07-10 13:37 UTC, jigneng1 commented on src/components/HintCards.tsx
> +function HintCards({ hints }: any) {
Done!

2022-07-11 14:34 UTC, jigneng1 commented
เสร็จเรียบร้อยแล้วนะ รอ merge @ThisTine

2022-07-22 09:42 UTC, ThisTine commented
@jigneng1 ฝาก merge develop ก่อน merge pr นี้นะ

2022-07-22 09:43 UTC, ThisTine approved these changes

2022-07-22 09:43 UTC, merged